version: '3'
services:

  wordpress:
    image: laravel-ddd
    container_name: laravel-ddd
    restart: always
    ports:
      - 8888:80

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password